create table employees(
	id serial primary key,
	employee_name varchar(50) not null
);

insert into employees(employee_name)
values 	('Jena Manuel'),
		('Lea Busch'),
		('Nu Beckman'),
		('Lowell Dabney'),
		('Annette Winchester'),
		('Stephenie Madrid-Earley'),
		('Leonarda Eason'),
		('Chara Soto'),
		('Dorla Angel'),
		('Sherril Walden'),
		('Toshiko Holloway'),
		('Melissa Jewett'),
		('Brandy Wicks'),
		('Duncan Alicea'),
		('Maricela Dow'),
		('Shanon Scanlon-Oakley'),
		('Phillis Cobbs'),
		('Leesa Browder'),
		('Ronda Griffis'),
		('Caryn Guthrie'),
		('Shera Wingate'),
		('Lesia Weatherford'),
		('Jeanne Engle'),
		('Juliann Robertson'),
		('Keira Steel-Cheng'),
		('Garland Weatherly'),
		('Alene Dias'),
		('Rosamond Slaton'),
		('Ok Brunson'),
		('Kori East'),
		('Meridith Crouch'),
		('Rozanne Messenger'),
		('Renata Paredes-Mcgrew'),
		('Porsha Veal'),
		('Lucio Pippin'),
		('Isaias Connolly'),
		('Erasmo Henderson'),
		('Dian Coffey-Vieira'),
		('Robby Richards'),
		('Fatima Burke'),
		('Velma Skipper'),
		('Lesha Rowley'),
		('Trevor Waite'),
		('Sigrid Findley'),
		('Halley Richards-Stinnett'),
		('Marvin Saenz'),
		('Hiedi Barry-Plummer'),
		('Chuck Tyree'),
		('Mckinley Garcia'),
		('Brent Kay'),
		('Leonida Brice'),
		('Antonetta Upchurch'),
		('Barrett Lenz'),
		('Caridad Arthur'),
		('Donald Curry'),
		('Cyndi Romo'),
		('Amado Valencia'),
		('Nell Halstead'),
		('Candy Cushman'),
		('Hattie Beauchamp'),
		('Forest Lorenzo'),
		('Dara Galvin'),
		('Jaimee Hanes'),
		('Samantha Schwarz'),
		('Renea Fulton'),
		('Betsy Houser'),
		('Penni Munoz'),
		('Bibi Bolton'),
		('Janna Wallace'),
		('Carlo Clifford');

create table salary(
	id serial primary key,
	monthly_salary int not null
);
	
insert into salary(monthly_salary)
values	(1000),
		(1100),
		(1200),
		(1300),
		(1400),
		(1500),
		(1600),
		(1700),
		(1800),
		(1900),
		(2000),
		(2100),
		(2200),
		(2300),
		(2400),
		(2500);

create table employee_salary(
	id serial primary key,
	employee_id int unique not null,
	salary_id int not null
);

insert into employee_salary(employee_id, salary_id)
values	(22, 2),
		(75, 14),
		(23, 5),
		(67, 8),
		(15, 4),
		(5, 4),
		(39, 12),
		(45, 15),
		(71, 3),
		(78, 6),
		(54, 12),
		(72, 9),
		(6, 2),
		(32, 15),
		(52, 8),
		(3, 6),
		(64, 11),
		(74, 14),
		(28, 10),
		(30, 4),
		(46, 10),
		(33, 12),
		(77, 8),
		(11, 16),
		(56, 4),
		(80, 1),
		(2, 7),
		(70, 15),
		(20, 8),
		(26, 12),
		(76, 3),
		(50, 8),
		(1, 1),
		(73, 11),
		(31, 6),
		(69, 14),
		(63, 11),
		(9, 13),
		(79, 11),
		(58, 8);


create table roles(
	id serial primary key,
	role_name int not null unique
);

alter table roles alter column role_name type varchar(30);

insert into roles(role_name)
values 	('Junior Python developer'),
		('Middle Python developer'),
		('Senior Python developer'),
		('Junior Java developer'),
		('Middle Java developer'),
		('Senior Java developer'),
		('Junior JavaScript developer'),
		('Middle JavaScript developer'),
		('Senior JavaScript developer'),
		('Junior Manual QA engineer'),
		('Middle Manual QA engineer'),
		('Senior Manual QA engineer'),
		('Project Manager'),
		('Designer'),
		('HR'),
		('CEO'),
		('Sales manager'),
		('Junior Automation QA engineer'),
		('Middle Automation QA engineer'),
		('Senior Automation QA engineer');

create table roles_employee(
	id serial primary key,
	employee_id int unique not null,
	role_id int not null,
	foreign key (employee_id)
		references employees(id),
	foreign key (role_id)
		references roles(id)
);

insert into roles_employee(employee_id, role_id)
values	(17, 8),
		(2, 2),
		(69, 2),
		(30, 4),
		(67, 10),
		(4, 3),
		(36, 12),
		(8, 15),
		(70, 5),
		(5, 5),
		(65, 7),
		(13, 1),
		(38, 15),
		(15, 10),
		(21, 11),
		(37, 6),
		(54, 10),
		(44, 4),
		(41, 8),
		(23, 4),
		(43, 4),
		(57, 16),
		(49, 6),
		(39, 15),
		(28, 10),
		(34, 15),
		(35, 3),
		(47, 3),
		(25, 7),
		(7, 3),
		(50, 15),
		(51, 6),
		(63, 11),
		(59, 15),
		(19, 8),
		(31, 4),
		(40, 5),
		(20, 5),
		(62, 16),
		(29, 7);


	
select * from roles_employee;